### ISSUE TITLE
Custom templates for nf-x-axis and nf-y-axis are not working

### ISSUE THREAD

**Issue by andrei1089** [Netflix/ember-nf-graph#106]
I'm running Ember 1.13 and custom templates are not working. As mentioned in this comment (https://github.com/Netflix/ember-nf-graph/commit/64e657cbc2da0cbf1a170f8ef794ae82b7a76376#commitcomment-12000510), `hasBlock` and `hasBlockParams` are available only in the template, so the `useTemplate` property is not computed correctly.

**Comment by blesh** [comment]
This addon doesn't currently support Ember 1.13. There are some APIs that were dropped in that version that his library relied on.

**Comment by jasonkriss** [comment]
@blesh I was just hit by this as well. I don't think it's limited to 1.13. [`hasBlock` and `hasBlockParams` are only available in templates contexts](https://github.com/emberjs/ember.js/issues/11741#issuecomment-121248949).

**Comment by blesh** [comment]
@jasonkriss what version of Ember are you using?

**Comment by jasonkriss** [comment]
@blesh I'm on 2.0.0.

**Comment by blesh** [comment]
@jasonkriss yeah, this addon won't work with 1.13 or higher. 1.13 broke compatibility with a couple of little-used (but not private) APIs these components used. My team at Netflix needs this addon to keep supporting 1.11 and 1.12, since that's the version our apps are on, and given how daunting the refactor looks to make it to 2.0, we're unlikely to invest much time to upgrade this addon to support 1.13 and higher at least for the time being.

Anyone is welcome to create PRs to add 2.0 support, of course, and I'll happily merge them if they don't break support for 1.11 and 1.12.

**Comment by blesh** [comment]
FWIW: I've added a [jj-abrams branch](https://github.com/netflix/ember-nf-graph/tree/jj-abrams) for anyone that wants to try their hand at supporting 2.0.

**Comment by jasonkriss** [comment]
@blesh got it! Thanks for providing a lil more context.
