### ISSUE TITLE
Add support for percentage based dimensions

### ISSUE THREAD

**Issue by miguelmota** [Netflix/ember-nf-graph#49]

**Comment by blesh** [comment]
percentage based dimensions for? The `nf-graph` container itself?

**Comment by miguelmota** [comment]
Yeah for the `nf-graph` component, instead of pixel based width/height

**Comment by blesh** [comment]
So this is tricky.

The pixel values passed to `width` and `height` are used to calculate the scale of the graphed elements. In order to get those, I'd need to check to see if what was passed happened to be a string ending with "%", then setup an event to detect when the SVG has resized. ... that's where this gets tricky. The only reliable way I know of to get when the SVG has been resized is to poll repeatedly and check it's computed size. This is because while a document resize event will help, it's not the only way to resize the parents of the SVG of the nf-graph component. If any DOM parent of the SVG element is updated, it will resize the SVG, and we need to know. Unfortunately there isn't a great event for that. MutationObservers may help, but aren't reliable in every browser, and may have performance implications... So I'd want to set them up *only* when the size was set to a percentage, and tear them down otherwise.

**Comment by blesh** [comment]
I'm not saying we're definitely *not* going to implement this. In fact, it might even end up being a requirement for the project this was birthed from. I'm really saying that this is a non-trivial change that could end up being buggy or slow on some platforms.

**Comment by blesh** [comment]
I'm adding `wontfix` to this and closing it, *for now*.

**BUT** I will keep this in mind because it's likely to come up on our app here.

**Comment by miguelmota** [comment]
@blesh I figured that would be case. Basically all the work would have to be invoked after the node is inserted in the DOM. Thanks anyway!

**Comment by ming-codes** [comment]
This could be the solution: [EmberSherpa/ember-element-resize-detector](https://github.com/EmberSherpa/ember-element-resize-detector)

**Comment by blesh** [comment]
@ming-codes as I recall, we used something like that to handle resizing these components at Netflix
